create or replace NONEDITIONABLE PROCEDURE "AAA_UPDATE" ( RELATION IN VARCHAR2, ATTR_VALUE IN INT, TUPLE_ID IN NUMBER ) IS
BEGIN
	EXECUTE IMMEDIATE 'call UPDATE_ATTR_AT('''||RELATION||''',''LLP'', '||ATTR_VALUE||', '||TUPLE_ID||')';
END AAA_UPDATE;


create or replace NONEDITIONABLE PROCEDURE ATTACK_SUPERSET (NO_TUPLES IN NUMBER, RELATION IN VARCHAR2) AS 
BEGIN
  FOR i IN 1..NO_TUPLES
  LOOP
     EXECUTE IMMEDIATE 'CALL INSERT_TUPLE('''||RELATION||''')';
  END LOOP;
  COMMIT;
END ATTACK_SUPERSET;


create or replace NONEDITIONABLE PROCEDURE ENV_GENERATION (SECRET_KEY IN VARCHAR2, K1 IN INT, K2 IN INT)  IS
BEGIN
    DBMS_OUTPUT.PUT_LINE(SYSTIMESTAMP);
    EXECUTE IMMEDIATE 'CALL NESTING_NEXT('||K2||')';
    EXECUTE IMMEDIATE 'CALL GS_GENERATION('''||SECRET_KEY||''','||K1||','||K2||')';
    DBMS_OUTPUT.PUT_LINE(SYSTIMESTAMP);
END ENV_GENERATION;



create or replace NONEDITIONABLE PROCEDURE "ERASE_TUPLES" (RELATION IN VARCHAR2, IDS IN VARCHAR2) IS 
BEGIN
    EXECUTE IMMEDIATE 'DELETE FROM '||RELATION||' WHERE ID = '||IDS;
END ERASE_TUPLES;


create or replace NONEDITIONABLE PROCEDURE  "INSERT_TUPLE" (RELATION IN VARCHAR2) IS 
  P_ELEVATION FLOAT(126); MAX_ELEVATION FLOAT(126); MIN_ELEVATION FLOAT(126);
	P_ASPECT FLOAT(126); MAX_ASPECT FLOAT(126); MIN_ASPECT FLOAT(126);
	P_SLOPE FLOAT(126); MAX_SLOPE FLOAT(126); MIN_SLOPE FLOAT(126);
	P_HOR_DIST_TO_HYDROLOGY FLOAT(126); MAX_HOR_DIST_TO_HYDROLOGY FLOAT(126); MIN_HOR_DIST_TO_HYDROLOGY FLOAT(126);
	P_VERT_DIST_TO_HYDROLOGY FLOAT(126); MAX_VERT_DIST_TO_HYDROLOGY FLOAT(126); MIN_VERT_DIST_TO_HYDROLOGY FLOAT(126);
	P_HOR_DIST_TO_ROADWAYS FLOAT(126); MAX_HOR_DIST_TO_ROADWAYS FLOAT(126); MIN_HOR_DIST_TO_ROADWAYS FLOAT(126);
	P_HILLSHADE_9AM FLOAT(126); MAX_HILLSHADE_9AM FLOAT(126); MIN_HILLSHADE_9AM FLOAT(126);
	P_HILLSHADE_NOON FLOAT(126); MAX_HILLSHADE_NOON FLOAT(126); MIN_HILLSHADE_NOON FLOAT(126);
	P_HILLSHADE_3PM FLOAT(126); MAX_HILLSHADE_3PM FLOAT(126); MIN_HILLSHADE_3PM FLOAT(126);
	P_HOR_DIST_TO_FIRE_POINTS FLOAT(126); MAX_HOR_DIST_TO_FIRE_POINTS FLOAT(126); MIN_HOR_DIST_TO_FIRE_POINTS FLOAT(126);
	P_WILDERNESS_AREA_1 NUMBER; MAX_WILDERNESS_AREA_1 NUMBER; MIN_WILDERNESS_AREA_1 NUMBER;
	P_WILDERNESS_AREA_2 NUMBER; MAX_WILDERNESS_AREA_2 NUMBER; MIN_WILDERNESS_AREA_2 NUMBER;
	P_WILDERNESS_AREA_3 NUMBER; MAX_WILDERNESS_AREA_3 NUMBER; MIN_WILDERNESS_AREA_3 NUMBER;
	P_WILDERNESS_AREA_4 NUMBER; MAX_WILDERNESS_AREA_4 NUMBER; MIN_WILDERNESS_AREA_4 NUMBER;
	P_SOIL_TYPE_01 NUMBER; MAX_SOIL_TYPE_01 NUMBER; MIN_SOIL_TYPE_01 NUMBER;
	P_SOIL_TYPE_02 NUMBER; MAX_SOIL_TYPE_02 NUMBER; MIN_SOIL_TYPE_02 NUMBER;
	P_SOIL_TYPE_03 NUMBER; MAX_SOIL_TYPE_03 NUMBER; MIN_SOIL_TYPE_03 NUMBER;
	P_SOIL_TYPE_04 NUMBER; MAX_SOIL_TYPE_04 NUMBER; MIN_SOIL_TYPE_04 NUMBER;
	P_SOIL_TYPE_05 NUMBER; MAX_SOIL_TYPE_05 NUMBER; MIN_SOIL_TYPE_05 NUMBER;
	P_SOIL_TYPE_06 NUMBER; MAX_SOIL_TYPE_06 NUMBER; MIN_SOIL_TYPE_06 NUMBER;
	P_SOIL_TYPE_07 NUMBER; MAX_SOIL_TYPE_07 NUMBER; MIN_SOIL_TYPE_07 NUMBER;
	P_SOIL_TYPE_08 NUMBER; MAX_SOIL_TYPE_08 NUMBER; MIN_SOIL_TYPE_08 NUMBER;
	P_SOIL_TYPE_09 NUMBER; MAX_SOIL_TYPE_09 NUMBER; MIN_SOIL_TYPE_09 NUMBER;
	P_SOIL_TYPE_10 NUMBER; MAX_SOIL_TYPE_10 NUMBER; MIN_SOIL_TYPE_10 NUMBER;
	P_SOIL_TYPE_11 NUMBER; MAX_SOIL_TYPE_11 NUMBER; MIN_SOIL_TYPE_11 NUMBER;
	P_SOIL_TYPE_12 NUMBER; MAX_SOIL_TYPE_12 NUMBER; MIN_SOIL_TYPE_12 NUMBER;
	P_SOIL_TYPE_13 NUMBER; MAX_SOIL_TYPE_13 NUMBER; MIN_SOIL_TYPE_13 NUMBER;
	P_SOIL_TYPE_14 NUMBER; MAX_SOIL_TYPE_14 NUMBER; MIN_SOIL_TYPE_14 NUMBER;
	P_SOIL_TYPE_15 NUMBER; MAX_SOIL_TYPE_15 NUMBER; MIN_SOIL_TYPE_15 NUMBER;
	P_SOIL_TYPE_16 NUMBER; MAX_SOIL_TYPE_16 NUMBER; MIN_SOIL_TYPE_16 NUMBER;
	P_SOIL_TYPE_17 NUMBER; MAX_SOIL_TYPE_17 NUMBER; MIN_SOIL_TYPE_17 NUMBER;
	P_SOIL_TYPE_18 NUMBER; MAX_SOIL_TYPE_18 NUMBER; MIN_SOIL_TYPE_18 NUMBER;
	P_SOIL_TYPE_19 NUMBER; MAX_SOIL_TYPE_19 NUMBER; MIN_SOIL_TYPE_19 NUMBER;
	P_SOIL_TYPE_20 NUMBER; MAX_SOIL_TYPE_20 NUMBER; MIN_SOIL_TYPE_20 NUMBER;
	P_SOIL_TYPE_21 NUMBER; MAX_SOIL_TYPE_21 NUMBER; MIN_SOIL_TYPE_21 NUMBER;
	P_SOIL_TYPE_22 NUMBER; MAX_SOIL_TYPE_22 NUMBER; MIN_SOIL_TYPE_22 NUMBER;
	P_SOIL_TYPE_23 NUMBER; MAX_SOIL_TYPE_23 NUMBER; MIN_SOIL_TYPE_23 NUMBER;
	P_SOIL_TYPE_24 NUMBER; MAX_SOIL_TYPE_24 NUMBER; MIN_SOIL_TYPE_24 NUMBER;
	P_SOIL_TYPE_25 NUMBER; MAX_SOIL_TYPE_25 NUMBER; MIN_SOIL_TYPE_25 NUMBER;
	P_SOIL_TYPE_26 NUMBER; MAX_SOIL_TYPE_26 NUMBER; MIN_SOIL_TYPE_26 NUMBER;
	P_SOIL_TYPE_27 NUMBER; MAX_SOIL_TYPE_27 NUMBER; MIN_SOIL_TYPE_27 NUMBER;
	P_SOIL_TYPE_28 NUMBER; MAX_SOIL_TYPE_28 NUMBER; MIN_SOIL_TYPE_28 NUMBER;
	P_SOIL_TYPE_29 NUMBER; MAX_SOIL_TYPE_29 NUMBER; MIN_SOIL_TYPE_29 NUMBER;
	P_SOIL_TYPE_30 NUMBER; MAX_SOIL_TYPE_30 NUMBER; MIN_SOIL_TYPE_30 NUMBER;
	P_SOIL_TYPE_31 NUMBER; MAX_SOIL_TYPE_31 NUMBER; MIN_SOIL_TYPE_31 NUMBER;
	P_SOIL_TYPE_32 NUMBER; MAX_SOIL_TYPE_32 NUMBER; MIN_SOIL_TYPE_32 NUMBER;
    P_SOIL_TYPE_33 NUMBER; MAX_SOIL_TYPE_33 NUMBER; MIN_SOIL_TYPE_33 NUMBER;
	P_SOIL_TYPE_34 NUMBER; MAX_SOIL_TYPE_34 NUMBER; MIN_SOIL_TYPE_34 NUMBER;
	P_SOIL_TYPE_35 NUMBER; MAX_SOIL_TYPE_35 NUMBER; MIN_SOIL_TYPE_35 NUMBER;
	P_SOIL_TYPE_36 NUMBER; MAX_SOIL_TYPE_36 NUMBER; MIN_SOIL_TYPE_36 NUMBER;
	P_SOIL_TYPE_37 NUMBER; MAX_SOIL_TYPE_37 NUMBER; MIN_SOIL_TYPE_37 NUMBER;
	P_SOIL_TYPE_38 NUMBER; MAX_SOIL_TYPE_38 NUMBER; MIN_SOIL_TYPE_38 NUMBER;
	P_SOIL_TYPE_39 NUMBER; MAX_SOIL_TYPE_39 NUMBER; MIN_SOIL_TYPE_39 NUMBER;
	P_SOIL_TYPE_40 NUMBER; MAX_SOIL_TYPE_40 NUMBER; MIN_SOIL_TYPE_40 NUMBER;
	P_COVER_TYPE NUMBER;  MAX_COVER_TYPE NUMBER; MIN_COVER_TYPE NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'SELECT MAX(ELEVATION), MAX(ASPECT), MAX(SLOPE), MAX(HOR_DIST_TO_HYDROLOGY), MAX(VERT_DIST_TO_HYDROLOGY),  MAX(HOR_DIST_TO_ROADWAYS), MAX(HILLSHADE_9AM), MAX(HILLSHADE_NOON), MAX(HILLSHADE_3PM), MAX(HOR_DIST_TO_FIRE_POINTS), MAX(WILDERNESS_AREA_1), MAX(WILDERNESS_AREA_2), MAX(WILDERNESS_AREA_3), MAX(WILDERNESS_AREA_4), MAX(SOIL_TYPE_01), MAX(SOIL_TYPE_02), MAX(SOIL_TYPE_03), MAX(SOIL_TYPE_04), MAX(SOIL_TYPE_05), MAX(SOIL_TYPE_06), MAX(SOIL_TYPE_07), MAX(SOIL_TYPE_08), MAX(SOIL_TYPE_09), MAX(SOIL_TYPE_10), MAX(SOIL_TYPE_11), MAX(SOIL_TYPE_12), MAX(SOIL_TYPE_13), MAX(SOIL_TYPE_14), MAX(SOIL_TYPE_15), MAX(SOIL_TYPE_16), MAX(SOIL_TYPE_17), MAX(SOIL_TYPE_18), MAX(SOIL_TYPE_19), MAX(SOIL_TYPE_20), MAX(SOIL_TYPE_21), MAX(SOIL_TYPE_22), MAX(SOIL_TYPE_23), MAX(SOIL_TYPE_24), MAX(SOIL_TYPE_25), MAX(SOIL_TYPE_26), MAX(SOIL_TYPE_27), MAX(SOIL_TYPE_28), MAX(SOIL_TYPE_29), MAX(SOIL_TYPE_30), MAX(SOIL_TYPE_31), MAX(SOIL_TYPE_32), MAX(SOIL_TYPE_33), MAX(SOIL_TYPE_34), MAX(SOIL_TYPE_35), MAX(SOIL_TYPE_36), MAX(SOIL_TYPE_37), MAX(SOIL_TYPE_38), MAX(SOIL_TYPE_39), MAX(SOIL_TYPE_40), MAX(COVER_TYPE) FROM '||RELATION INTO MAX_ELEVATION, MAX_ASPECT, MAX_SLOPE, MAX_HOR_DIST_TO_HYDROLOGY, MAX_VERT_DIST_TO_HYDROLOGY, MAX_HOR_DIST_TO_ROADWAYS, MAX_HILLSHADE_9AM, MAX_HILLSHADE_NOON, MAX_HILLSHADE_3PM, MAX_HOR_DIST_TO_FIRE_POINTS, MAX_WILDERNESS_AREA_1, MAX_WILDERNESS_AREA_2, MAX_WILDERNESS_AREA_3, MAX_WILDERNESS_AREA_4, MAX_SOIL_TYPE_01, MAX_SOIL_TYPE_02, MAX_SOIL_TYPE_03, MAX_SOIL_TYPE_04, MAX_SOIL_TYPE_05, MAX_SOIL_TYPE_06, MAX_SOIL_TYPE_07, MAX_SOIL_TYPE_08, MAX_SOIL_TYPE_09, MAX_SOIL_TYPE_10, MAX_SOIL_TYPE_11, MAX_SOIL_TYPE_12, MAX_SOIL_TYPE_13, MAX_SOIL_TYPE_14, MAX_SOIL_TYPE_15, MAX_SOIL_TYPE_16, MAX_SOIL_TYPE_17, MAX_SOIL_TYPE_18, MAX_SOIL_TYPE_19, MAX_SOIL_TYPE_20, MAX_SOIL_TYPE_21, MAX_SOIL_TYPE_22, MAX_SOIL_TYPE_23, MAX_SOIL_TYPE_24, MAX_SOIL_TYPE_25, MAX_SOIL_TYPE_26, MAX_SOIL_TYPE_27, MAX_SOIL_TYPE_28, MAX_SOIL_TYPE_29, MAX_SOIL_TYPE_30, MAX_SOIL_TYPE_31, MAX_SOIL_TYPE_32, MAX_SOIL_TYPE_33, MAX_SOIL_TYPE_34, MAX_SOIL_TYPE_35, MAX_SOIL_TYPE_36, MAX_SOIL_TYPE_37, MAX_SOIL_TYPE_38, MAX_SOIL_TYPE_39, MAX_SOIL_TYPE_40, MAX_COVER_TYPE; 
  EXECUTE IMMEDIATE 'SELECT MIN(ELEVATION), MIN(ASPECT), MIN(SLOPE), MIN(HOR_DIST_TO_HYDROLOGY), MIN(VERT_DIST_TO_HYDROLOGY),  MIN(HOR_DIST_TO_ROADWAYS), MIN(HILLSHADE_9AM), MIN(HILLSHADE_NOON), MIN(HILLSHADE_3PM), MIN(HOR_DIST_TO_FIRE_POINTS), MIN(WILDERNESS_AREA_1), MIN(WILDERNESS_AREA_2), MIN(WILDERNESS_AREA_3), MIN(WILDERNESS_AREA_4), MIN(SOIL_TYPE_01), MIN(SOIL_TYPE_02), MIN(SOIL_TYPE_03), MIN(SOIL_TYPE_04), MIN(SOIL_TYPE_05), MIN(SOIL_TYPE_06), MIN(SOIL_TYPE_07), MIN(SOIL_TYPE_08), MIN(SOIL_TYPE_09), MIN(SOIL_TYPE_10), MIN(SOIL_TYPE_11), MIN(SOIL_TYPE_12), MIN(SOIL_TYPE_13), MIN(SOIL_TYPE_14), MIN(SOIL_TYPE_15), MIN(SOIL_TYPE_16), MIN(SOIL_TYPE_17), MIN(SOIL_TYPE_18), MIN(SOIL_TYPE_19), MIN(SOIL_TYPE_20), MIN(SOIL_TYPE_21), MIN(SOIL_TYPE_22), MIN(SOIL_TYPE_23), MIN(SOIL_TYPE_24), MIN(SOIL_TYPE_25), MIN(SOIL_TYPE_26), MIN(SOIL_TYPE_27), MIN(SOIL_TYPE_28), MIN(SOIL_TYPE_29), MIN(SOIL_TYPE_30), MIN(SOIL_TYPE_31), MIN(SOIL_TYPE_32), MIN(SOIL_TYPE_33), MIN(SOIL_TYPE_34), MIN(SOIL_TYPE_35), MIN(SOIL_TYPE_36), MIN(SOIL_TYPE_37), MIN(SOIL_TYPE_38), MIN(SOIL_TYPE_39), MIN(SOIL_TYPE_40), MIN(COVER_TYPE) FROM '||RELATION INTO MIN_ELEVATION, MIN_ASPECT, MIN_SLOPE, MIN_HOR_DIST_TO_HYDROLOGY, MIN_VERT_DIST_TO_HYDROLOGY, MIN_HOR_DIST_TO_ROADWAYS, MIN_HILLSHADE_9AM, MIN_HILLSHADE_NOON, MIN_HILLSHADE_3PM, MIN_HOR_DIST_TO_FIRE_POINTS, MIN_WILDERNESS_AREA_1, MIN_WILDERNESS_AREA_2, MIN_WILDERNESS_AREA_3, MIN_WILDERNESS_AREA_4, MIN_SOIL_TYPE_01, MIN_SOIL_TYPE_02, MIN_SOIL_TYPE_03, MIN_SOIL_TYPE_04, MIN_SOIL_TYPE_05, MIN_SOIL_TYPE_06, MIN_SOIL_TYPE_07, MIN_SOIL_TYPE_08, MIN_SOIL_TYPE_09, MIN_SOIL_TYPE_10, MIN_SOIL_TYPE_11, MIN_SOIL_TYPE_12, MIN_SOIL_TYPE_13, MIN_SOIL_TYPE_14, MIN_SOIL_TYPE_15, MIN_SOIL_TYPE_16, MIN_SOIL_TYPE_17, MIN_SOIL_TYPE_18, MIN_SOIL_TYPE_19, MIN_SOIL_TYPE_20, MIN_SOIL_TYPE_21, MIN_SOIL_TYPE_22, MIN_SOIL_TYPE_23, MIN_SOIL_TYPE_24, MIN_SOIL_TYPE_25, MIN_SOIL_TYPE_26, MIN_SOIL_TYPE_27, MIN_SOIL_TYPE_28, MIN_SOIL_TYPE_29, MIN_SOIL_TYPE_30, MIN_SOIL_TYPE_31, MIN_SOIL_TYPE_32, MIN_SOIL_TYPE_33, MIN_SOIL_TYPE_34, MIN_SOIL_TYPE_35, MIN_SOIL_TYPE_36, MIN_SOIL_TYPE_37, MIN_SOIL_TYPE_38, MIN_SOIL_TYPE_39, MIN_SOIL_TYPE_40, MIN_COVER_TYPE; 

  SELECT round(dbms_random.value(MIN_ELEVATION,MAX_ELEVATION)) INTO P_ELEVATION from dual;
  SELECT round(dbms_random.value(MIN_ASPECT,MAX_ASPECT)) INTO P_ASPECT from dual;
  SELECT round(dbms_random.value(MIN_SLOPE,MAX_SLOPE)) INTO P_SLOPE from dual;
  SELECT round(dbms_random.value(MIN_HOR_DIST_TO_HYDROLOGY,MAX_HOR_DIST_TO_HYDROLOGY)) INTO P_HOR_DIST_TO_HYDROLOGY from dual;
  SELECT round(dbms_random.value(MIN_VERT_DIST_TO_HYDROLOGY,MAX_VERT_DIST_TO_HYDROLOGY)) INTO P_VERT_DIST_TO_HYDROLOGY from dual;
  SELECT round(dbms_random.value(MIN_HOR_DIST_TO_ROADWAYS,MAX_HOR_DIST_TO_ROADWAYS)) INTO P_HOR_DIST_TO_ROADWAYS from dual;
  SELECT round(dbms_random.value(MIN_HILLSHADE_9AM,MAX_HILLSHADE_9AM)) INTO P_HILLSHADE_9AM from dual;
  SELECT round(dbms_random.value(MIN_HILLSHADE_NOON,MAX_HILLSHADE_NOON)) INTO P_HILLSHADE_NOON from dual;
  SELECT round(dbms_random.value(MIN_HILLSHADE_3PM,MAX_HILLSHADE_3PM)) INTO P_HILLSHADE_3PM from dual;
  SELECT round(dbms_random.value(MIN_HOR_DIST_TO_FIRE_POINTS,MAX_HOR_DIST_TO_FIRE_POINTS)) INTO P_HOR_DIST_TO_FIRE_POINTS from dual;
  SELECT round(dbms_random.value(MIN_WILDERNESS_AREA_1,MAX_WILDERNESS_AREA_1)) INTO P_WILDERNESS_AREA_1 from dual;
  SELECT round(dbms_random.value(MIN_WILDERNESS_AREA_2,MAX_WILDERNESS_AREA_2)) INTO P_WILDERNESS_AREA_2 from dual;
  SELECT round(dbms_random.value(MIN_WILDERNESS_AREA_3,MAX_WILDERNESS_AREA_3)) INTO P_WILDERNESS_AREA_3 from dual;
  SELECT round(dbms_random.value(MIN_WILDERNESS_AREA_4,MAX_WILDERNESS_AREA_4)) INTO P_WILDERNESS_AREA_4 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_01,MAX_SOIL_TYPE_01)) INTO P_SOIL_TYPE_01 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_02,MAX_SOIL_TYPE_02)) INTO P_SOIL_TYPE_02 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_03,MAX_SOIL_TYPE_03)) INTO P_SOIL_TYPE_03 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_04,MAX_SOIL_TYPE_04)) INTO P_SOIL_TYPE_04 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_05,MAX_SOIL_TYPE_05)) INTO P_SOIL_TYPE_05 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_06,MAX_SOIL_TYPE_06)) INTO P_SOIL_TYPE_06 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_07,MAX_SOIL_TYPE_07)) INTO P_SOIL_TYPE_07 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_08,MAX_SOIL_TYPE_08)) INTO P_SOIL_TYPE_08 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_09,MAX_SOIL_TYPE_09)) INTO P_SOIL_TYPE_09 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_10,MAX_SOIL_TYPE_10)) INTO P_SOIL_TYPE_10 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_11,MAX_SOIL_TYPE_11)) INTO P_SOIL_TYPE_11 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_12,MAX_SOIL_TYPE_12)) INTO P_SOIL_TYPE_12 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_13,MAX_SOIL_TYPE_13)) INTO P_SOIL_TYPE_13 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_14,MAX_SOIL_TYPE_14)) INTO P_SOIL_TYPE_14 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_15,MAX_SOIL_TYPE_15)) INTO P_SOIL_TYPE_15 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_16,MAX_SOIL_TYPE_16)) INTO P_SOIL_TYPE_16 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_17,MAX_SOIL_TYPE_17)) INTO P_SOIL_TYPE_17 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_18,MAX_SOIL_TYPE_18)) INTO P_SOIL_TYPE_18 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_19,MAX_SOIL_TYPE_19)) INTO P_SOIL_TYPE_19 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_20,MAX_SOIL_TYPE_20)) INTO P_SOIL_TYPE_20 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_21,MAX_SOIL_TYPE_21)) INTO P_SOIL_TYPE_21 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_22,MAX_SOIL_TYPE_22)) INTO P_SOIL_TYPE_22 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_23,MAX_SOIL_TYPE_23)) INTO P_SOIL_TYPE_23 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_24,MAX_SOIL_TYPE_24)) INTO P_SOIL_TYPE_24 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_25,MAX_SOIL_TYPE_25)) INTO P_SOIL_TYPE_25 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_26,MAX_SOIL_TYPE_26)) INTO P_SOIL_TYPE_26 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_27,MAX_SOIL_TYPE_27)) INTO P_SOIL_TYPE_27 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_28,MAX_SOIL_TYPE_28)) INTO P_SOIL_TYPE_28 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_29,MAX_SOIL_TYPE_29)) INTO P_SOIL_TYPE_29 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_30,MAX_SOIL_TYPE_30)) INTO P_SOIL_TYPE_30 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_31,MAX_SOIL_TYPE_31)) INTO P_SOIL_TYPE_31 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_32,MAX_SOIL_TYPE_32)) INTO P_SOIL_TYPE_32 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_33,MAX_SOIL_TYPE_33)) INTO P_SOIL_TYPE_33 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_34,MAX_SOIL_TYPE_34)) INTO P_SOIL_TYPE_34 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_35,MAX_SOIL_TYPE_35)) INTO P_SOIL_TYPE_35 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_36,MAX_SOIL_TYPE_36)) INTO P_SOIL_TYPE_36 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_37,MAX_SOIL_TYPE_37)) INTO P_SOIL_TYPE_37 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_38,MAX_SOIL_TYPE_38)) INTO P_SOIL_TYPE_38 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_39,MAX_SOIL_TYPE_39)) INTO P_SOIL_TYPE_39 from dual;
  SELECT round(dbms_random.value(MIN_SOIL_TYPE_40,MAX_SOIL_TYPE_40)) INTO P_SOIL_TYPE_40 from dual;
  SELECT round(dbms_random.value(MIN_COVER_TYPE,MAX_COVER_TYPE)) INTO P_COVER_TYPE from dual;

  EXECUTE IMMEDIATE 'INSERT INTO '||RELATION||' (ELEVATION, ASPECT, SLOPE, HOR_DIST_TO_HYDROLOGY, VERT_DIST_TO_HYDROLOGY, HOR_DIST_TO_ROADWAYS, HILLSHADE_9AM, HILLSHADE_NOON, HILLSHADE_3PM, HOR_DIST_TO_FIRE_POINTS, WILDERNESS_AREA_1, WILDERNESS_AREA_2, WILDERNESS_AREA_3, WILDERNESS_AREA_4, SOIL_TYPE_01, SOIL_TYPE_02, SOIL_TYPE_03, SOIL_TYPE_04, SOIL_TYPE_05, SOIL_TYPE_06, SOIL_TYPE_07, SOIL_TYPE_08, SOIL_TYPE_09, SOIL_TYPE_10, SOIL_TYPE_11, SOIL_TYPE_12, SOIL_TYPE_13, SOIL_TYPE_14, SOIL_TYPE_15, SOIL_TYPE_16, SOIL_TYPE_17, SOIL_TYPE_18, SOIL_TYPE_19, SOIL_TYPE_20, SOIL_TYPE_21, SOIL_TYPE_22, SOIL_TYPE_23, SOIL_TYPE_24, SOIL_TYPE_25, SOIL_TYPE_26, SOIL_TYPE_27, SOIL_TYPE_28, SOIL_TYPE_29, SOIL_TYPE_30, SOIL_TYPE_31, SOIL_TYPE_32, SOIL_TYPE_33, SOIL_TYPE_34, SOIL_TYPE_35, SOIL_TYPE_36, SOIL_TYPE_37, SOIL_TYPE_38, SOIL_TYPE_39, SOIL_TYPE_40, COVER_TYPE) VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13,:14,:15,:16,:17,:18,:19,:20,:21,:22,:23,:24,:25,:26,:27,:28,:29,:30,:31,:32,:33,:34,:35,:36,:37,:38,:39,:40,:41,:42,:43,:44,:45,:46,:47,:48,:49,:50,:51,:52,:53,:54,:55)' USING P_ELEVATION, P_ASPECT, P_SLOPE, P_HOR_DIST_TO_HYDROLOGY, P_VERT_DIST_TO_HYDROLOGY, P_HOR_DIST_TO_ROADWAYS, P_HILLSHADE_9AM, P_HILLSHADE_NOON, P_HILLSHADE_3PM, P_HOR_DIST_TO_FIRE_POINTS, P_WILDERNESS_AREA_1, P_WILDERNESS_AREA_2, P_WILDERNESS_AREA_3, P_WILDERNESS_AREA_4, P_SOIL_TYPE_01, P_SOIL_TYPE_02, P_SOIL_TYPE_03, P_SOIL_TYPE_04, P_SOIL_TYPE_05, P_SOIL_TYPE_06, P_SOIL_TYPE_07, P_SOIL_TYPE_08, P_SOIL_TYPE_09, P_SOIL_TYPE_10, P_SOIL_TYPE_11, P_SOIL_TYPE_12, P_SOIL_TYPE_13, P_SOIL_TYPE_14, P_SOIL_TYPE_15, P_SOIL_TYPE_16, P_SOIL_TYPE_17, P_SOIL_TYPE_18, P_SOIL_TYPE_19, P_SOIL_TYPE_20, P_SOIL_TYPE_21, P_SOIL_TYPE_22, P_SOIL_TYPE_23, P_SOIL_TYPE_24, P_SOIL_TYPE_25, P_SOIL_TYPE_26, P_SOIL_TYPE_27, P_SOIL_TYPE_28, P_SOIL_TYPE_29, P_SOIL_TYPE_30, P_SOIL_TYPE_31, P_SOIL_TYPE_32, P_SOIL_TYPE_33, P_SOIL_TYPE_34, P_SOIL_TYPE_35, P_SOIL_TYPE_36, P_SOIL_TYPE_37, P_SOIL_TYPE_38, P_SOIL_TYPE_39, P_SOIL_TYPE_40, P_COVER_TYPE;

END INSERT_TUPLE;



create or replace NONEDITIONABLE PROCEDURE "LOGIC_TUPLE_ERASE" (RELATION IN VARCHAR2, IDS IN VARCHAR2) IS 
BEGIN
    EXECUTE IMMEDIATE 'UPDATE '||RELATION||' SET DELETED = 1 WHERE ID = '||IDS;
END LOGIC_TUPLE_ERASE;



create or replace NONEDITIONABLE PROCEDURE "POS_RANDOMIZER" (VPK IN VARCHAR2, IMAGE_HEIGHT IN INT, IMAGE_WIDTH IN INT, H OUT INT, W OUT INT) IS 
BEGIN
  SELECT ORA_HASH(VPK,IMAGE_HEIGHT,1) INTO H FROM dual;
  SELECT ORA_HASH(VPK,IMAGE_WIDTH,2) INTO W FROM dual;
END POS_RANDOMIZER;



create or replace NONEDITIONABLE PROCEDURE  "RESP_ATTR" (RELATION IN VARCHAR2, ATTR_NAME IN VARCHAR2) IS
BEGIN
  EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET ATTR_RESP='||ATTR_NAME;
END RESP_ATTR;



create or replace NONEDITIONABLE PROCEDURE  "RESP_LLP" (RELATION IN VARCHAR2) IS
BEGIN
  EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET LLP_RESP = LLP';
END RESP_LLP;



create or replace NONEDITIONABLE PROCEDURE "RESTART_LOGIC_ERASE" IS 
BEGIN
    UPDATE COVERTYPE_A SET DELETED = 0;
END RESTART_LOGIC_ERASE;



create or replace NONEDITIONABLE PROCEDURE RTW_ASSIGN_VPK (RELATION IN VARCHAR2, SECRET_KEY IN VARCHAR2) AS 
BEGIN
	EXECUTE IMMEDIATE 'UPDATE ' || RELATION || ' SET VPK = CREATE_VPK(ID, ''' || SECRET_KEY || ''')';
END RTW_ASSIGN_VPK;



create or replace NONEDITIONABLE PROCEDURE "RTW_GENERATE_CONSFACTOR" (RELATION IN VARCHAR2, TUPLE_FRACT IN NUMBER) IS 
BEGIN
  EXECUTE IMMEDIATE 'UPDATE ' ||RELATION|| ' SET TUPL_FACTOR = MOD(VPK,'||TUPLE_FRACT||')';
END RTW_GENERATE_CONSFACTOR;


create or replace NONEDITIONABLE PROCEDURE "RTW_GENERATE_VPK" (RELATION IN VARCHAR2, TUPLE_ID IN NUMBER, VPK_SOURCE IN INT, SECRET_KEY IN VARCHAR2) IS 
vpk INT;
BEGIN
  SELECT ORA_HASH(sys.dbms_obfuscation_toolkit.md5(input_string => VPK_SOURCE || SECRET_KEY)) AS VPK INTO vpk FROM dual;

  EXECUTE IMMEDIATE 'UPDATE ' ||RELATION|| ' SET VPK =:1 WHERE ID =:2' USING vpk, TUPLE_ID;

END RTW_GENERATE_VPK;



create or replace NONEDITIONABLE PROCEDURE RTW_INSERT_TUPLE (RELATION IN VARCHAR2, EXT IN INT) IS 
    P_COPER_ID FLOAT(126); P_AR_ID FLOAT(126);
	P_AF_ID FLOAT(126); P_TIPO_CORSO_COD VARCHAR2(20); 
	P_CDS_COD VARCHAR2(20); P_NOME_CDS VARCHAR2(300); 
	P_REGDID_COD VARCHAR2(20); P_PDS_COD VARCHAR2(20);
	P_PDS_DES VARCHAR2(70); P_AA_OFF_ID FLOAT(126);  
	P_AF_GEN_COD VARCHAR2(20); P_AF_GEN_DES VARCHAR2(200); 
	P_ANNO_CORSO NUMBER; P_SETT_COD VARCHAR2(20); 
	P_PESO FLOAT(126); P_ORE_ATT_FRONT FLOAT(126); 
	P_PART_STU_DES VARCHAR2(30); P_DES_TIPO_CICLO VARCHAR2(20); 
	P_MATRICOLA VARCHAR2(20); P_COGNOME VARCHAR2(30);
	P_NOME VARCHAR2(40); P_DIP_DES VARCHAR2(100); 
	P_TIPO_COPER_COD VARCHAR2(20); P_MODDID VARCHAR2(40);
	P_CONTENUTI_ENG CLOB; P_TESTI_RIF_ENG CLOB; 
	P_OBIETT_FORM_ENG CLOB; P_PREREQ_ENG CLOB;
	P_MOD_VER_APPR_ENG CLOB; P_ALTRO_ENG CLOB;
	P_METODI_DID_ENG CLOB; P_LINGUA_INS_ENG VARCHAR2(20); 
	P_MOD_VER_DETT_ENG CLOB; P_RIS_APPR_ENG CLOB;
	P_DETTAGLIO_ORE VARCHAR2(50); P_VPK NUMBER;
	P_TUPL_FACTOR NUMBER(2,0); P_B_EMB_SK CLOB;
	P_B_EXT_SK CLOB; P_EMB_MOD_VER_DETT_ENG CLOB; 
	P_EMB_RIS_APPR_ENG CLOB; P_EMB_CONTENUTI_ENG CLOB; 
	P_EMB_OBIETT_FORM_ENG CLOB; P_NEW_CONC CLOB;
    
    P_PRODUCT_ID VARCHAR2(10); P_USER_ID VARCHAR2(20); 
	P_PROFILE_NAME VARCHAR2(100); P_HELPFULNESS_NUMERATOR NUMBER;
	P_HELPFULNESS_DENOMINATOR NUMBER; P_SCORE NUMBER;
	P_TIME VARCHAR2(10); P_SUMMARY CLOB;
	P_TEXT CLOB; P_EMB_TEXT CLOB;

BEGIN 
    P_COPER_ID := NULL; P_AR_ID := NULL;
	P_AF_ID := NULL; P_TIPO_CORSO_COD := NULL;
	P_CDS_COD := NULL; P_NOME_CDS := NULL;
	P_REGDID_COD := NULL; P_PDS_COD := NULL;
	P_PDS_DES := NULL; P_AA_OFF_ID := NULL;
	P_AF_GEN_COD := NULL; P_AF_GEN_DES := NULL;
	P_ANNO_CORSO := NULL; P_SETT_COD := NULL;
	P_PESO := NULL; P_ORE_ATT_FRONT := NULL;
	P_PART_STU_DES := NULL; P_DES_TIPO_CICLO := NULL;
	P_MATRICOLA := NULL; P_COGNOME := NULL;
	P_NOME := NULL; P_DIP_DES := NULL;
	P_TIPO_COPER_COD := NULL; P_MODDID := NULL;
	P_CONTENUTI_ENG := NULL; P_TESTI_RIF_ENG := NULL;
	P_OBIETT_FORM_ENG := NULL; P_PREREQ_ENG := NULL;
	P_MOD_VER_APPR_ENG := NULL; P_ALTRO_ENG := NULL;
	P_METODI_DID_ENG := NULL; P_LINGUA_INS_ENG := NULL;
	P_MOD_VER_DETT_ENG := NULL; P_RIS_APPR_ENG := NULL;
	P_DETTAGLIO_ORE := NULL; P_VPK := NULL;
	P_TUPL_FACTOR := NULL; P_B_EMB_SK := NULL;
	P_B_EXT_SK := NULL; P_EMB_MOD_VER_DETT_ENG := NULL;
	P_EMB_RIS_APPR_ENG := NULL; P_EMB_CONTENUTI_ENG := NULL;
	P_EMB_OBIETT_FORM_ENG := NULL; P_NEW_CONC := NULL;
    
    P_PRODUCT_ID := NULL; P_USER_ID := NULL; 
	P_PROFILE_NAME := NULL; P_HELPFULNESS_NUMERATOR := NULL;
	P_HELPFULNESS_DENOMINATOR := NULL; P_SCORE := NULL;
	P_TIME := NULL; P_SUMMARY := NULL;
	P_TEXT := NULL; P_EMB_TEXT := NULL;
    
    IF EXT = 1 THEN

        SELECT EMB_MOD_VER_DETT_ENG INTO P_EMB_MOD_VER_DETT_ENG FROM (SELECT EMB_MOD_VER_DETT_ENG FROM UNIVE_SYLLABUS ORDER BY dbms_random.value) WHERE rownum = 1;
        SELECT EMB_RIS_APPR_ENG     INTO P_EMB_RIS_APPR_ENG     FROM (SELECT EMB_RIS_APPR_ENG     FROM UNIVE_SYLLABUS ORDER BY dbms_random.value) WHERE rownum = 1;
        SELECT EMB_CONTENUTI_ENG    INTO P_EMB_CONTENUTI_ENG    FROM (SELECT EMB_CONTENUTI_ENG    FROM UNIVE_SYLLABUS ORDER BY dbms_random.value) WHERE rownum = 1;
        SELECT EMB_OBIETT_FORM_ENG  INTO P_EMB_OBIETT_FORM_ENG  FROM (SELECT EMB_OBIETT_FORM_ENG  FROM UNIVE_SYLLABUS ORDER BY dbms_random.value) WHERE rownum = 1;
    
    
        EXECUTE IMMEDIATE 'INSERT INTO UNIVE_SYLLABUS (COPER_ID, AR_ID, AF_ID, TIPO_CORSO_COD, CDS_COD, NOME_CDS, REGDID_COD, PDS_COD, PDS_DES, AA_OFF_ID, AF_GEN_COD, AF_GEN_DES, ANNO_CORSO, SETT_COD, PESO, ORE_ATT_FRONT, PART_STU_DES, DES_TIPO_CICLO, MATRICOLA, COGNOME, NOME, DIP_DES, TIPO_COPER_COD, MODDID, CONTENUTI_ENG, TESTI_RIF_ENG, OBIETT_FORM_ENG, PREREQ_ENG, MOD_VER_APPR_ENG, ALTRO_ENG, METODI_DID_ENG, LINGUA_INS_ENG, MOD_VER_DETT_ENG, RIS_APPR_ENG, DETTAGLIO_ORE, VPK, TUPL_FACTOR, B_EMB_SK, B_EXT_SK, EMB_MOD_VER_DETT_ENG, EMB_RIS_APPR_ENG, EMB_CONTENUTI_ENG, EMB_OBIETT_FORM_ENG, NEW_CONC) VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13,:14,:15,:16,:17,:18,:19,:20,:21,:22,:23,:24,:25,:26,:27,:28,:29,:30,:31,:32,:33,:34,:35,:36,:37,:38,:39,:40,:41,:42,:43,:44)' USING P_COPER_ID, P_AR_ID, P_AF_ID, P_TIPO_CORSO_COD, P_CDS_COD, P_NOME_CDS, P_REGDID_COD, P_PDS_COD, P_PDS_DES, P_AA_OFF_ID, P_AF_GEN_COD, P_AF_GEN_DES, P_ANNO_CORSO, P_SETT_COD, P_PESO, P_ORE_ATT_FRONT, P_PART_STU_DES, P_DES_TIPO_CICLO, P_MATRICOLA, P_COGNOME, P_NOME, P_DIP_DES, P_TIPO_COPER_COD, P_MODDID, P_CONTENUTI_ENG, P_TESTI_RIF_ENG, P_OBIETT_FORM_ENG, P_PREREQ_ENG, P_MOD_VER_APPR_ENG, P_ALTRO_ENG, P_METODI_DID_ENG, P_LINGUA_INS_ENG, P_MOD_VER_DETT_ENG, P_RIS_APPR_ENG, P_DETTAGLIO_ORE, P_VPK, P_TUPL_FACTOR, P_B_EMB_SK, P_B_EXT_SK, P_EMB_MOD_VER_DETT_ENG, P_EMB_RIS_APPR_ENG, P_EMB_CONTENUTI_ENG, P_EMB_OBIETT_FORM_ENG, P_NEW_CONC;
    ELSE
        SELECT EMB_TEXT  INTO P_EMB_TEXT  FROM (SELECT EMB_TEXT  FROM TEX_DOCUMENTS ORDER BY dbms_random.value) WHERE rownum = 1;
        
        EXECUTE IMMEDIATE 'INSERT INTO TEX_DOCUMENTS (PRODUCT_ID, USER_ID, PROFILE_NAME, HELPFULNESS_NUMERATOR, HELPFULNESS_DENOMINATOR, SCORE, TEX_DOCUMENTS.TIME, SUMMARY, TEX_DOCUMENTS.TEXT, VPK, TUPL_FACTOR, B_EMB_SK, B_EXT_SK, EMB_TEXT) VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13,:14)' USING P_PRODUCT_ID, P_USER_ID, P_PROFILE_NAME, P_HELPFULNESS_NUMERATOR, P_HELPFULNESS_DENOMINATOR, P_SCORE, P_TIME, P_SUMMARY, P_TEXT, P_VPK, P_TUPL_FACTOR, P_B_EMB_SK, P_B_EXT_SK, P_EMB_TEXT;
    END IF;
END RTW_INSERT_TUPLE;



create or replace NONEDITIONABLE PROCEDURE "RTW_UPDATE_ATTR" ( RELATION IN VARCHAR2, ATTR_NAME IN VARCHAR2, ATTR_VALUE IN CLOB, TUPLE_ID IN NUMBER ) IS
BEGIN
  IF TUPLE_ID > 0 THEN
    EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET '||ATTR_NAME||'=:1 WHERE id =:2' USING ATTR_VALUE, TUPLE_ID;
  ELSE
    EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET '||ATTR_NAME||'=:1' USING ATTR_VALUE;
  END IF;
END RTW_UPDATE_ATTR;



create or replace NONEDITIONABLE PROCEDURE "RTW_UPDATE_ATTR_AT" ( RELATION IN VARCHAR2, ATTR_NAME IN VARCHAR2, TUPLE_ID IN NUMBER ) IS
    ATTR_VAL CLOB;

BEGIN
    ATTR_VAL := NULL;
    EXECUTE IMMEDIATE 'SELECT '||ATTR_NAME||' FROM (SELECT '||ATTR_NAME||' FROM '||RELATION||' ORDER BY dbms_random.value) WHERE rownum = 1' INTO ATTR_VAL;
   
    IF TUPLE_ID > 0 THEN
        EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET '||ATTR_NAME||'=:1 WHERE id =:2' USING ATTR_VAL, TUPLE_ID;
    ELSE
        EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET '||ATTR_NAME||'=:1' USING ATTR_VAL;
    END IF;
END RTW_UPDATE_ATTR_AT;



create or replace NONEDITIONABLE PROCEDURE "SIMULATE_RESP" (RELATION IN VARCHAR2, ATTR_NAME IN VARCHAR2, MIN_VAL IN INT, MAX_VAL IN INT) IS 
  id_cursor sys_refcursor;
  attr_val FLOAT(126);
  id_row INT;

BEGIN
  OPEN id_cursor FOR 'SELECT ID AS IDENT FROM '||RELATION||' ORDER BY ID';

  LOOP
    FETCH id_cursor INTO id_row;
    EXIT WHEN id_cursor%NOTFOUND;

    SELECT round(dbms_random.value(MIN_VAL,MAX_VAL)) INTO attr_val from dual;
    EXECUTE IMMEDIATE 'CALL UPDATE_ATTR_AT('''||RELATION||''','''||ATTR_NAME||''', '||attr_val||', '||id_row||')';
  END LOOP;

  CLOSE id_cursor;

END SIMULATE_RESP;


create or replace NONEDITIONABLE PROCEDURE  "UPDATE_ATTR_AT" ( RELATION IN VARCHAR2, ATTR_NAME IN VARCHAR2, ATTR_VALUE IN INT, TUPLE_ID IN NUMBER ) IS
BEGIN
  IF TUPLE_ID > 0 THEN
    EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET '||ATTR_NAME||'=:1 WHERE id =:2' USING ATTR_VALUE, TUPLE_ID;
  ELSE
    EXECUTE IMMEDIATE 'UPDATE '||RELATION|| ' SET '||ATTR_NAME||'=:1' USING ATTR_VALUE;
  END IF;
END UPDATE_ATTR_AT;


create or replace NONEDITIONABLE PROCEDURE "UPDATE_CONF" (SK IN VARCHAR2, TF IN INT ) IS
BEGIN
    EXECUTE IMMEDIATE 'UPDATE COVERTYPE_A SET VPK_PERS = CREATE_VPK(LLP,'''||SK||'''), 
    CONS_PERS =  MOD(CREATE_VPK(LLP,'''||SK||'''),'||TF||'),
    SEED_PERS =  MOD(CREATE_VPK(LLP,'''||SK||'''),'||TF||'+1)';
END UPDATE_CONF;














