--------------------------------------------------------
--  DDL for Table COVERTYPE_A
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COVERTYPE_A" 
   (	"ID" NUMBER(*,0), 
	"ELEVATION" FLOAT(126), 
	"ASPECT" FLOAT(126), 
	"SLOPE" FLOAT(126), 
	"HOR_DIST_TO_HYDROLOGY" FLOAT(126), 
	"VERT_DIST_TO_HYDROLOGY" FLOAT(126), 
	"HOR_DIST_TO_ROADWAYS" FLOAT(126), 
	"HILLSHADE_9AM" FLOAT(126), 
	"HILLSHADE_NOON" FLOAT(126), 
	"HILLSHADE_3PM" FLOAT(126), 
	"HOR_DIST_TO_FIRE_POINTS" FLOAT(126), 
	"WILDERNESS_AREA_1" NUMBER(*,0), 
	"WILDERNESS_AREA_2" NUMBER(*,0), 
	"WILDERNESS_AREA_3" NUMBER(*,0), 
	"WILDERNESS_AREA_4" NUMBER(*,0), 
	"SOIL_TYPE_01" NUMBER(*,0), 
	"SOIL_TYPE_02" NUMBER(*,0), 
	"SOIL_TYPE_03" NUMBER(*,0), 
	"SOIL_TYPE_04" NUMBER(*,0), 
	"SOIL_TYPE_05" NUMBER(*,0), 
	"SOIL_TYPE_06" NUMBER(*,0), 
	"SOIL_TYPE_07" NUMBER(*,0), 
	"SOIL_TYPE_08" NUMBER(*,0), 
	"SOIL_TYPE_09" NUMBER(*,0), 
	"SOIL_TYPE_10" NUMBER(*,0), 
	"SOIL_TYPE_11" NUMBER(*,0), 
	"SOIL_TYPE_12" NUMBER(*,0), 
	"SOIL_TYPE_13" NUMBER(*,0), 
	"SOIL_TYPE_14" NUMBER(*,0), 
	"SOIL_TYPE_15" NUMBER(*,0), 
	"SOIL_TYPE_16" NUMBER(*,0), 
	"SOIL_TYPE_17" NUMBER(*,0), 
	"SOIL_TYPE_18" NUMBER(*,0), 
	"SOIL_TYPE_19" NUMBER(*,0), 
	"SOIL_TYPE_20" NUMBER(*,0), 
	"SOIL_TYPE_21" NUMBER(*,0), 
	"SOIL_TYPE_22" NUMBER(*,0), 
	"SOIL_TYPE_23" NUMBER(*,0), 
	"SOIL_TYPE_24" NUMBER(*,0), 
	"SOIL_TYPE_25" NUMBER(*,0), 
	"SOIL_TYPE_26" NUMBER(*,0), 
	"SOIL_TYPE_27" NUMBER(*,0), 
	"SOIL_TYPE_28" NUMBER(*,0), 
	"SOIL_TYPE_29" NUMBER(*,0), 
	"SOIL_TYPE_30" NUMBER(*,0), 
	"SOIL_TYPE_31" NUMBER(*,0), 
	"SOIL_TYPE_32" NUMBER(*,0), 
	"SOIL_TYPE_33" NUMBER(*,0), 
	"SOIL_TYPE_34" NUMBER(*,0), 
	"SOIL_TYPE_35" NUMBER(*,0), 
	"SOIL_TYPE_36" NUMBER(*,0), 
	"SOIL_TYPE_37" NUMBER(*,0), 
	"SOIL_TYPE_38" NUMBER(*,0), 
	"SOIL_TYPE_39" NUMBER(*,0), 
	"SOIL_TYPE_40" NUMBER(*,0), 
	"COVER_TYPE" NUMBER(*,0), 
	"VPK_II" NUMBER, 
	"LLP" NUMBER, 
	"NEW_COL" FLOAT(126), 
	"ELEVATION2" FLOAT(126), 
	"ASPECT2" FLOAT(126), 
	"SLOPE2" FLOAT(126), 
	"HOR_DIST_TO_HYDROLOGY2" FLOAT(126), 
	"VERT_DIST_TO_HYDROLOGY2" FLOAT(126), 
	"HOR_DIST_TO_ROADWAYS2" FLOAT(126), 
	"HILLSHADE_9AM2" FLOAT(126), 
	"HILLSHADE_NOON2" FLOAT(126), 
	"HILLSHADE_3PM2" FLOAT(126), 
	"HOR_DIST_TO_FIRE_POINTS2" FLOAT(126), 
	"PREV_A4" NUMBER, 
	"PREV_A3" NUMBER, 
	"PREV_A2" NUMBER, 
	"PREV_A1" NUMBER, 
	"NEXT_A1" NUMBER, 
	"NEXT_A2" NUMBER, 
	"NEXT_A3" NUMBER, 
	"NEXT_A4" NUMBER, 
	"G_I" NUMBER, 
	"G_II" NUMBER, 
	"PREV_A5" NUMBER, 
	"NEXT_A5" NUMBER, 
	"DELETED" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."ELEVATION" IS 'Elevation in meters';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."ASPECT" IS 'Aspect in degrees azimuth';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SLOPE" IS 'Slope in degrees';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."HOR_DIST_TO_HYDROLOGY" IS 'Horz Dist to nearest surface water features';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."VERT_DIST_TO_HYDROLOGY" IS 'Vert Dist to nearest surface water features';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."HOR_DIST_TO_ROADWAYS" IS 'Horz Dist to nearest roadway';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."HILLSHADE_9AM" IS 'Hillshade index at 9am, summer solstice';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."HILLSHADE_NOON" IS 'Hillshade index at noon, summer soltice';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."HILLSHADE_3PM" IS 'Hillshade index at 3pm, summer solstice';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."HOR_DIST_TO_FIRE_POINTS" IS 'Horz Dist to nearest wildfire ignition points';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."WILDERNESS_AREA_1" IS 'Wilderness area designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."WILDERNESS_AREA_2" IS 'Wilderness area designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."WILDERNESS_AREA_3" IS 'Wilderness area designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."WILDERNESS_AREA_4" IS 'Wilderness area designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_01" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_02" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_03" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_04" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_05" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_06" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_07" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_08" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_09" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_10" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_11" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_12" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_13" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_14" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_15" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_16" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_17" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_18" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_19" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_20" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_21" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_22" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_23" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_24" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_25" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_26" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_27" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_28" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_29" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_30" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_31" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_32" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_33" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_34" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_35" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_36" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_37" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_38" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_39" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."SOIL_TYPE_40" IS 'Soil Type designation';
   COMMENT ON COLUMN "SYSTEM"."COVERTYPE_A"."COVER_TYPE" IS 'Forest Cover Type designation...';
--------------------------------------------------------
--  DDL for Index COVERTYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COVERTYPE_PK" ON "SYSTEM"."COVERTYPE_A" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger COVERTYPE_A_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SYSTEM"."COVERTYPE_A_TRG" 
BEFORE INSERT ON COVERTYPE_A 
REFERENCING NEW AS NEW 
FOR EACH ROW 
BEGIN
  SELECT ID_SEQ.nextval INTO :NEW.ID FROM dual;
END;

/
ALTER TRIGGER "SYSTEM"."COVERTYPE_A_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table COVERTYPE_A
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COVERTYPE_A" ADD CONSTRAINT "COVERTYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SYSTEM"."COVERTYPE_A" MODIFY ("ID" NOT NULL ENABLE);
